use_frameworks!
platform :ios, '11.3'

target 'SCPKIHelper_Example' do
  pod 'SCPKIHelper', :path => '../'

  target 'SCPKIHelper_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
