use_frameworks!

target 'SCPKIHelper_Example' do
  pod 'SCPKIHelper', :path => '../'

  target 'SCPKIHelper_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
